[phases.setup]
nixPkgs = ["...", "rustup", "gcc", "pkg-config", "openssl"]

[phases.build]
cmds = ["rustup default stable", "cargo build --release"]

[start]
cmd = "./target/release/apex-singularity"
